# Generated by Django 4.1.4 on 2022-12-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_student_mobile_no_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
