# Generated by Django 4.1.4 on 2022-12-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_notificationmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'verbose_name_plural': '10. Notifications Assignment'},
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='notif_text',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='notif_created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Notification Time'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='notif_for',
            field=models.CharField(max_length=200, verbose_name='Notification For'),
        ),
    ]
