# Generated by Django 4.1.4 on 2022-12-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_notificationmodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationModel',
        ),
    ]
