# Generated by Django 4.1.4 on 2022-12-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_quiz_quizquestions_coursequiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestions',
            old_name='questions',
            new_name='question',
        ),
    ]
