# Generated by Django 4.1.4 on 2023-01-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_attemptquiz_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptquiz',
            options={'verbose_name_plural': '14. Attempt Quiz'},
        ),
    ]
