# Generated by Django 4.1.4 on 2023-01-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_attemptquiz_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttemptQuiz',
        ),
    ]
